import IBank from "dto/Kongapay/IBank";
import IDocument from "./IDocument";
import IMadate from "./IMadate";
import IPersonBankAccount from "./IPersonBankAccount";
import IPersonCard from "./IPersonCard";
import IPersonWallet from "./IPersonWallet";

interface IPerson {
  uuid: string;
  first_name: string;
  last_name: string;
  other: string | null;
  email: string;
  phone: string;
  last_login: Date;
  bvn: string;
  dob: Date;
  sift_ratings: string | null;
  sift_score: string | null;
  sift_workflow: string | null;
  created_at: Date;
  status: string;
  password_reset_token: string | null;
  payout_limit: string;
  government_issued_id?: IDocument;
  utility_bill?: IDocument;
  group_user_id: number;
  user_id: number;
  group_id: number;
  group_name: string;
  referral_code: string;
  group_username: string;
  group_phone: string;
  group_email: string;
  terminal_id: string | null;
  role_id: string;
  test_public_key: string;
  live_public_key: string | null;
  test_private_key: string;
  live_private_key: string | null;
  qr_code_url: string | null;
  kyc_level: string;
  kyc_level_name: string;
  logo_url: string | null;
  parent_group_id: number | null;
  account_type_id: string | null;
  account_type_name: string;
  role_features: string;
  role_name: string;
  token: string;
  finger_print: string | null;
  transaction_pin: string;
  required_detail_update: number;
  wallets: Array<IPersonWallet>;
  cards: Array<IPersonCard>;
  mandates: Array<IMadate>;
  banks: Array<IPersonBankAccount>;
  referrer_url: string;
}

export default IPerson;
