import IProduct from "dto/KongaOnline/IProduct";

interface ICustomPage {
  page_title: string;
  section_title: string;
  filename: string;
  image_alt: string;
  link: string;
  link_target: string;
  variant: number;
  theme: number;
  html_box: string | null;
  seo_text: string | null;
  subtitle1: string;
  subtitle2: string;
  subtitle3: string;
  subtitle4: string;
  subtitle5: string;
  description1: string;
  description2: string;
  description3: string;
  description4: string;
  description5: string;
  link1: string;
  linkUrl1: string;
  link2: string;
  linkUrl2: string;
  link3: string;
  linkUrl3: string;
  link4: string;
  linkUrl4: string;
  link5: string;
  linkUrl5: string;
  buttonText: string;
  buttonTextUrl: string;
  imageSource1: string;
  imageAltText1: string;
  imageLink1: string;
  imageSource2: string;
  imageAltText2: string;
  imageLink2: string;
  imageSource3: string;
  imageAltText3: string;
  imageLink3: string;
  imageSource4: string;
  imageAltText4: string;
  imageLink4: string;
  imageSource5: string;
  imageAltText5: string;
  imageLink5: string;
  videoSource: string;
  bgColor1: string;
  bgColor2: string;
  bgColor3: string;
  bgImageUrl: string;
  product?: Array<IProduct>;
}

export default ICustomPage;
